files:
  train_data: train_mnist.pt
  test_data: test_mnist.pt
  model: test_mnist.pt

paths:
  data_path: ${hydra:runtime.cwd}/data/processed
  model_path: ${hydra:runtime.cwd}/models

params:
  model: cnn
  batch_size: 128
  x_dim: 784
  hidden_dim: 400
  latent_dim: 20
  lr: 0.01
  epochs: 1
  seed: 7 